version: "3"

services:
  cloud-sms-server:
    container_name: cloud-sms-server
    image: ramesesinc/osiris3-core:1.0
    restart: always
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: 10m
    environment:
      TZ: "Asia/Manila"
    env_file:
      - ./env.conf
      - ../../_res/env.conf
      - ../../_custom/env.conf
    ports:
      - "9170:8070"
    volumes:
      - ./services:/apps/server/services

      - ../../_custom/datasources/smsds:/apps/server/services/datasources/mainds
      - ../../_custom/output:/apps/server/output
